Output hlist.gif
Set Shell zsh
Sleep 1s
Hide
Type "go run ./..."
Enter
Show
Sleep 1.5s
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Left
Sleep 500ms
Left
Sleep 500ms
Left
Sleep 500ms
Left
Sleep 500ms
Left
Sleep 500ms
Type "]"
Sleep 500ms
Type "]"
Sleep 500ms
Type "]"
Sleep 500ms
Type "["
Sleep 500ms
Type "["
Sleep 500ms
Type "["
Sleep 500ms
Type "/"
Sleep 500ms
Type "dream"
Sleep 500ms
Enter
Sleep 1s

